[package]
name = "tetris"
version = "0.1.0"
authors = ["etoledom <etoledom@icloud.com>"]
edition = "2018"

[dependencies]
utilities = { path = "../utilities" }
tetris_core = "0.2.1"
piston_window = "0.127.0"
rand = "0.8.5"
